# -*- coding: utf-8 -*-
"""Stable Diffusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jS_U61IVpfPBK4c8o9_TW_pSs4wAXJOL
"""

''' Components of Stable Diffusion
1. Variational AutoEncoder (VAE)
2. UNet Denoising Network
3. Schedule
4. Text Encoder (Conditioning): either a CLIP or T5 encoder
'''